### ISSUE TITLE
Introduce parAll

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#119]
Into the companion object of `IO`, introduce the following `parAll` method:

```scala
final def parAll[E, A, M[X] <: TraversableOnce[X]](
    as: M[IO[E, A]]
  )(implicit cbf: CanBuildFrom[M[IO[E, A]], A, M[A]]): IO[E, M[A]]
```

This method should run all values in parallel. For now, it can be build by using the `par` method on the `IO` class.

Clues as to how to build this (given the complex type signature) can be found by examining the implementation of `forkAll`, which uses a similar type signature.

**Comment by jdegoes** [comment]
@Vilkina has volunteered to take this ticket; although helpers are welcome to contribute!

**Comment by Vilkina** [comment]
Status: examining the implementation of forkAll.

**Comment by sideeffffect** [comment]
What should be the naming convention?
`parAll` rhymes with `forkAll` and `raceAll`. I originally went with `parSequence`, because it rhymes with `parTraverse` and it is essentially a *par*allel implementation of `sequence`.
But I don't have strong attachment to any of the names. What do you guys think?

**Comment by Vilkina** [comment]
this was my ticket :(

**Comment by Vilkina** [comment]
Please, don't show implementation.

**Comment by sideeffffect** [comment]
I'm sorry @Vilkina :( I noticed John's and your post only after I submitted the PR
