### ISSUE TITLE
Future interop needs simplified signature or add to documentation

### ISSUE THREAD

**Issue by baank** [scalaz/scalaz-zio#146]
Another newbie question/issue. When using the Future interop this is the signature I end up with:

val x = Future { "something" }
IO.fromFuture(() => x)(ec = scala.concurrent.ExecutionContext.Implicits.global)

When really I would've hoped for something more like:
IO.fromFuture(x)

Is it worth having an overloaded method with an easier version like below ?

**Comment by ktonga** [comment]
That signature is precisely to avoid the mistake your snippet is making.

`Future` is eager, that means as soon as you call `Future.apply` the effect has been performed, that's not a desired behavior in **Pure FP** _(which ZIO encourages)_. In this case `x` must be defined as a `def` instead of as a `val` so evaluation is deferred to the time when the `IO` is run.

Also you have to be explicit on which EC you wanna use, having it as implicit in std is a bad practice we don't want to cargo cult.

Your example would be something like this:

```scala
val myEC = ...

def x() = Future { "something" }
IO.fromFuture(x)(myEC)
```

**Comment by baank** [comment]
Can we change this ticket to just cutting/pasting what you said and putting in the readme ?

I think a lot of people will make the stupid mistake I did. And you explained it really well.

**Comment by ktonga** [comment]
BTW you are right about this should be added to the docs. I have to work on #77 and I definitely will include that explanation.

**Comment by ktonga** [comment]
Closing since we already have a ticket for interop docs
