### ISSUE TITLE
Implement support for Scala.js

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#22]
- [ ] Extract `Platform` from `RTS` to encapsulate platform-specific functionality.
 - [ ] Create `PlatformJs` and `PlatformJvm`
 - [ ] Create `RTS` using `PlatformJs`, and `RTS` using `PlatformJvm`
 - [ ] Make all tests pass, or split up tests if some require multithreading

**Comment by fabianpage** [comment]
So we would had something like that:

shared:
  - trait Platform
  - trait RTSI { self: Platform }
  - trait RTSO {self: Platform }

jvm:
  - PlatformJVM extends Platform
  - trait RTS extends RTSI with PlatformJVM
  - private object RTS extends RTSO with PlatformJVM

js:
  - PlatformJVM extends Platform
  - trait RTS extends RTSI with PlatformJVM
  - private object RTS extends RTSO with PlatformJVM

Then we should be able to have the RTSSpec in shared.

**Comment by fabianpage** [comment]
As far as i see the main problem is the missing executors. AtomicReference seems to exit in Scala.js 

So the question is how to nicely seperate that part out.

**Comment by jdegoes** [comment]
@fabianpage We just need an interface that has `submit` and implement that using `setImmediate` / `setTimeout(0)` in Javascript.

**Comment by jdegoes** [comment]
Ah, we also need the scheduled executors bit. So we need a `submitLater` with a `Duration` and implement that using `setTimeout`.

**Comment by fabianpage** [comment]
So submit[A](block: => A): Unit and submitLater[A](block: => A, duration:Duration): Unit is all we need to implement the RTS?

Then i will try tomorrow to implement that.

**Comment by jdegoes** [comment]
@fabianpage I think that's probably correct. Although once you dive into the details, there may be a few other minor things we have to pull out into `Platform`.

**Comment by scalavision** [comment]
Is there any progress on this? Or is it blocked because of other additions / changes in the RTS? I'd love to start playing with Zio in the browser :-)

**Comment by scalavision** [comment]
Testing the library in a ScalaJS client, made the following compile linking errors:

```
non-existent method java.lang.Runtime.addShutdownHook(java.lang.Thread)scala.Unit
```

```
non-existent class java.util.WeakHashMap
```

```
 non-existent method java.util.concurrent.atomic.AtomicReference.wait()scala.Unit
```

**Comment by jdegoes** [comment]
@scalavision We would create a `newWeakSet` inside `Platform`, and fake it out in Javascript. In Javascript, it would be an ordinary `Array`, probably.

**Comment by jdegoes** [comment]
The `App` can have a separate `JS` implementation which does not use `addShutdownHook`.

**Comment by scalavision** [comment]
Thanks John! I am a bit blocked due to work at the moment. Will have a look at it as soon as I get the opportunity :-)

**Comment by scalavision** [comment]
@jdegoes How should `runSync` in RTS be handled? I understand that this method will have to block if necessary, I am not sure if that is possible to do in a nice way in Javascript? It seems like there are some implementations of something similar in jQuery (Deferred), in async.js and in Ecmascript 2017 etc. but it is probably a bit challenging to make work.

https://github.com/scalavision/scalaz-zio/blob/7e194e85713100e6379490c72e955f9e43f85b93/core/js/src/main/scala/scalaz/zio/RTS.scala#L236

Except from this, I made the hello world example given in the docs run in the browser! It will throw exception due to this function calling runSync:

https://github.com/scalavision/scalaz-zio/blob/7e194e85713100e6379490c72e955f9e43f85b93/core/js/src/main/scala/scalaz/zio/App.scala#L38

But after throwing the exception, the app continues to run happily .. I am not sure how to implement all of this using async, it was a lot of hackery just to make this compile. Probably would have to rethink the way to do this in Javascript ...  
 
Leaving out `IO.sync` and `runSync` for ScalaJS verison is probably a bit difficult or not?

**Comment by scalavision** [comment]
I'll look into the Javascript Event Loop, see what I kind find :-)

**Comment by jdegoes** [comment]
`runSync` cannot be implemented in Javascript. For now it would be fine to throw an exception if someone calls that method, although eventually we should separate the RTS using a common base (`CommonRTS`) and not have the `unsafeRun` / `unsafeRunSync` in the Javascript version.

**Comment by ritschwumm** [comment]
i guess that means i cannot implement an old-style event listener in the browser which returns true or false to the caller, right? would i still be able to call Event.preventDefault near the end of an IO operation with a guarantee i won't be shuffled through any setTimeout  before that?

**Comment by scalavision** [comment]
I am really not sure how this will turn out in practice :-) I have only tried to print to the console. I am not an expert on the internals of RTS either, but it seems to me that the codeblock of the IO will be put to run asynchronoulsy on the event loop via setTimeout. So your `preventDefault` can be called inside the IO right? Sorry, if I misunderstand what your want to achieve here ... 

My take on this, was to try to create a minimalistic Streaming library, as described in the Red Book, pulling IO events / states, or whatever, updating my DOM tree etc. accordingly, but not sure if I need to though ..

There are a lot of ways to do this I think, but I agree, that the first step is to refactor out common stuff into the CommonRTS, and make ZIO library run in the browser.
