### ISSUE TITLE
Support par/parWith in Managed

### ISSUE THREAD

**Issue by iravid** [scalaz/scalaz-zio#257]
See discussion in #252 for details

**Comment by mijicd** [comment]
I have started to work on this issue in #303. However, as agreed with @iravid, I have closed the PR until I understand the approach proposed in [this comment](https://github.com/scalaz/scalaz-zio/pull/252#issuecomment-423510265).

@jdegoes could you please explain the idea in 2-3 short sentences so that I can continue working on this, and hopefully reopen the PR with the proper implementation.
