### ISSUE TITLE
Add `MonadIO`

### ISSUE THREAD

**Issue by regiskuckaertz** [scalaz/scalaz-zio#365]
I think that ZIO has zero dependencies was a brilliant design decision, but it forces users to either commit to using `IO` everywhere in their program or depend on the whole cats/scalaz machinery in order to write more generic code.

Writing a program in a final encoding style should be library-agnostic, as it is a construction that is entirely encapsulated by the language. With that in mind, and in the same zero-dependency spirit, I believe the effort required of users to write tagless-final programs and commit to ZIO at the end of the world can be kept to a strict minimum:

```scala
trait MonadIO[F[+_, +_]] {
  def lift[E, A](io: IO[E, A]): F[E, A]
  def map[E, A, B](f: A => B)(fa : F[E, A]): F[E, B]
  def flatMap[E, A, B](f: A => F[E,  B])(fa : F[E, A]): F[E, B]
}
trait MonadIOMono[F[+_]] {
  def lift[E, A](io: IO[E, A]): F[A]
  def map[A, B](f: A => B)(fa : F[A]): F[B]
  def flatMap[A, B](f: A => F[B])(fa : F[A]): F[B]
}
```

These type classes witness that an `F` is powerful enough to interpret any interaction with the outside world and also perform side-effects of its own.

**Comment by jdegoes** [comment]
Why `map` and `flatMap`?

Here's how I see it:

All we _really_ need is `lift`. Because then a user programs in `IO`, and lifts it up to some polymorphic `F` type (possibly Monix, possibly EitherT with Cats Effect IO, possibly Cats BIO, etc.).

Then users make `lift` the final call in all their APIs:

```scala
def foo[F[+_, +_]: MonadIO] = MonadIO[F].lift(...)

def bar[F[+_, +_]: MonadIO] = MonadIO[F].lift(...)
```


The drawback is that a user cannot call their own API.

That is, they cannot call `foo` from inside `bar`. Which means they need some `internalFoo` which returns `IO`:

```scala
private def internalFoo: IO[Exception, Unit] = ...

def foo[F[+_, +_]: MonadIO] = MonadIO[F].lift(internalFoo)

def bar[F[+_, +_]: MonadIO] = MonadIO[F].lift(...)
```

Now in the worst case they need private and public versions of all their API methods: the private one can be used internally, the public API merely "lifts" the private API into a polymorphic `F`.

This is not the end of the world, but it's not great.

Now if you add `map` and `flatMap`, they can do a bit more, but where does it stop? If you add those, then soon you'll want to add `redeem` so you can do error handling, and then you'll want to add more, and finally you'll end up with #263. Which would not be easy to implement on a third-party effect data type.

Maybe one stops at the set of things which are universal: `Monad`. That's a reason for adding `map` and `flatMap` (and `point`). But that just reduces the pain, but does not eliminate it. Because if `foo` produces some error that `bar` needs to recover from again, then we're back at the old private / public API.

So I'm torn on whether to make `lift` the only method, which basically mandates a public / private API, or whether to add a few things to make the situation more ambiguous. Overall, I lean toward just having `lift` as it seems less arbitrary, but I'm really not sure.

**Comment by kaishh** [comment]
I think we could just leave this to cats-effect and use quantification + [covariant syntax extensions](https://gist.github.com/kaishh/e070d96e3b3b10a6f200542714585639#file-quantified-scala-L39) to deal with the error type. We also need an extension to model termination/run as that's the only thing cats-effect doesn't model, but that's it. I've been testing this way in a private codebase for awhile and it seems ok.

**Comment by kaishh** [comment]
@jdegoes 
Sure, I was going to ask if I can submit a PR ;) Though I think quantification is too general to be in interop, is it ok to create a `scalaz-zio-quantified` module?

**Comment by regiskuckaertz** [comment]
> Why map and flatMap?

I just wondered: "_what's the bare minimum requirement one needs so that they can write MTL-style programs with effects?_" Of course the answer is `Monad`, perhaps `MonadError`. With that people can go very far, creating mini-DSLs ad nauseum. There is a trivial embedding of ZIO into itself, but they also have the choice of another implementation (or even several of them). But yeah, `lift` is stricly speaking all that is needed.
