### ISSUE TITLE
Create Scala.js version of OneShot.scala

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#426]
`OneShot` is a variable that can be set once. On the JVM, the getter blocks. We need a Scala.js version that does not block, whose getter simply returns the value of the variable (or throws an exception if it's null).

`OneShot` can currently be found in `/shared/src/main/scala/scalaz/zio/internal/OneShot.scala`. We should move this version to `/jvm/src/main/scala/scalaz/zio/internal/OneShot.scala`, and add the Javascript version in `/js/src/main/scala/scalaz/zio/internal/OneShot.scala`.

**Comment by bbroeksema** [comment]
Looking at it, but need a bit of guidance:

1. As I understand the project structure, code under core/shared is shared by jvm and js projects under core.
2. There are a bunch of files in core/shared which depend on OneShot

Consequently, moving OneShot to core/jvm/... are no longer compiling. Should all those files move to core/jvm as well? If not, how than should be solved, because adding a dep on jvm from shared is not what is desired either it seems to me.

Additionally, it's not completely clear to me how to test the ScalaJs version. Some input on that would be appreciated as well.

**Comment by wongelz** [comment]
@bbroeksema 

1. core/shared is shared by jvm and js projects, but conversely, core/shared can also call methods in jvm and js; if there are corresponding copies in each with the same package/class/method signatures. See how MutableConcurrentQueue (in shared) can use OneElementConcurrentQueue and RingBuffer (which reside in jvm/js). So IO can stay in shared and it will still compile (although Intellij highlighting may think otherwise).

2. Specifically, this bit is what breaks in ScalaJS: `this.wait(timeout)`, because java.lang.Object#wait(long timeout) does not exist in ScalaJS.

**Comment by bbroeksema** [comment]
@wongelz is there some documentation somewhere on how to test the ScalaJS part? I have literely 0 experience with ScalaJS, so it's not clear to me how to trigger the error above.

**Comment by wongelz** [comment]
@bbroeksema The commands to run tests separately for ScalaJS/JVM on the core module are: 
`sbt 'coreJS/test'`
`sbt 'coreJVM/test`

If you set up a simple unit test that performs a set and a get on a OneShot you should see it pass for JVM and fail with linking errors for JS.

**Comment by bbroeksema** [comment]
Well, @wongelz that's weird. See #520. That one actually compiles and runs the test succesfully for me locally.

```sbt:scalaz-zio> coreJS/test
[info] Compiling 1 Scala source to /home/cm75lm/git/scalaz-zio/core/js/target/scala-2.12/test-classes ...
[info] Done compiling.
[info] Fast optimizing /home/cm75lm/git/scalaz-zio/core/js/target/scala-2.12/scalaz-zio-test-fastopt.js
[info] MutableConcurrentQueueSpec
...
[info] OneShotSpec
[info]     Make a new OneShot
[info]      + set must accept a non-null value.
[info] Total for specification OneShotSpec
[info] Finished in 22 ms
[info] 1 example, 0 failure, 0 error
[info] Passed: Total 6, Failed 0, Errors 0, Passed 6
```

**Comment by bbroeksema** [comment]
@jdegoes huis issue can be closed I guess as me pr got merged.

**Comment by NeQuissimus** [comment]
Closing. See #520 for details.
