### ISSUE TITLE
Introduce Void

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#43]
Using `Nothing` is too painful. We should introduce a simple `Void`:

```scala
abstract final class Void {
  def absurd[A]: A
}
```

And use wherever `Nothing` is currently used.

**Comment by env0der** [comment]
See #45, hopefully that's what you've meant.

**Comment by ktonga** [comment]
The name `Void` is a bit overused IMO, scalaz has it and even there is one in java which already caused some confusion. While using zio as an standalone lib will be no issue, but when using it together with scalaz base it will be confusing.

I suggest, since this inhabited type will be used only to signal the absence of errors, that we call it `NoError` (or anything similar)

WDYT @jdegoes ?

**Comment by ktonga** [comment]
We also should probably start using `Unexceptional` (which i would like to rename to `Infallible`) wherever `IO[NoError, A]` is used.

**Comment by alexknvl** [comment]
I believe we made a mistake by introducing `Void` as a newtype.

### Name clash with java.lang.Void

It is really annoying.

### Dead code warnings
Dead code warnings are not real warnings in pure code. The only case where they make sense is if you "accidentally" create a "value" of type `Nothing`, e.g.
```scala
def foo: Unit = {
  doStuff
  val x = throw new Foo // A "value" of type Nothing
  doMoreStuff(x) // Dead code
}
```

It does not make any sense in pure code, because the only way we can obtain a value of type `Nothing` is if someone gives it to us:
```scala
def thisWillNeverRun(v: Nothing): Int = {
  (v : List[List[Int]]).head.head
}
```
this code is indeed dead, but how is it a useful warning? What should we be worried about? That we *accidentally* put `Nothing` as an argument?

### Resolution issues
The original motivation for `Void` (at least in `leibniz`) was to work around the implicit resolution bugs, that apparently existed back in the day. There is no indication that they still exist in 2.12.6, and regardless of that,
```scala
type Bottom <: Nothing
```
would work equally well w.r.t. implicit resolution.

### Scalaz depending on ZIO for Void

It's not a problem, but it is confusing IMHO.
