### ISSUE TITLE
reduce compareAndSet call. 

### ISSUE THREAD

**Issue by hepin1989** [scalaz/scalaz-zio#461]
If the Promise is already completed, then there is no need for allocation.

```scala
 final def get: IO[E, A] =
    IO.async0[E, A](k => {
      var result: Async[E, A] = null.asInstanceOf[Async[E, A]]
      var retry               = true

      while (retry) {
        val oldState = state.get

        val newState = oldState match {
          case Pending(joiners) =>
            result = Async.maybeLater(interruptJoiner(k))

            Pending(k :: joiners)
          case s @ Done(value) =>
            result = Async.now[E, A](value)

            s
        }

        retry = !state.compareAndSet(oldState, newState)
      }

      result
    })
```
could be 

```scala
  final def get: IO[E, A] = state.get() match {
    case Done(value) => IO.done(value)
    case _ => 
      ...
  }
```

and if it's already done,there is no need to do the CAS too

**Comment by jdegoes** [comment]
Excellent goal, however, `state.get()` is not a function (it's non-deterministic because it reads from mutable memory), so it must be called inside an `IO` to preserve referential transparency, so this is not a safe refactoring. You could put it into `IO.sync` but then you will need to flatten the nested `IO` which will be slower than the current approach.

**Comment by hepin1989** [comment]
@jdegoes For the `Promise` shouldn't it be safe?

**Comment by jdegoes** [comment]
No, it's never safe. In fact, `get` could be turned into a `val` to make that point clear. It's not an effectful function, it's an ordinary `IO` value.

**Comment by hepin1989** [comment]
great to make it a `val` @jdegoes
