### ISSUE TITLE
add Chymyst to zio benchmarks

### ISSUE THREAD

**Issue by lemastero** [scalaz/scalaz-zio#556]
@winitzki have done interesting work - implementation of Join-Calculus on JVM
There are some [benchmark in Chymyst/chymyst-core](https://github.com/Chymyst/chymyst-core/tree/master/benchmark/src/main/scala/io/chymyst/benchmark)

I wonder if some of zio benchmarks could include also this approach to concurrency.

I'd love :heart:  to see the numbers :)

**Comment by winitzki** [comment]
See this video for some very simple benchmarks https://www.youtube.com/watch?v=SgAneCA262o&list=PLcoadSpY7rHWh23clCzL0SuJ4fAtzVzTb&index=11  and code https://github.com/Chymyst/Chymyst/blob/master/src/test/scala/io/chymyst/lab/ChymystForkJoin.scala   - the result is that `zio` fibonacci benchmark is a bit slower than other implementations.  But the Chemical Machine implementation, when done completely naively, is much slower due to overheads (might be improved in a future version, but right now that's what it is). I do have a Chemical Machine implementation that's slighly faster than Scala `Future`s, but I am cheating a bit (I'm using Java atomic integer and a mutable array, in order to avoid using `Future.sequence`).

**Comment by lemastero** [comment]
I think I am trying compare apples with oranges in here. Closing for now.
Thank you for insight @winitzki :bowing_man:
