### ISSUE TITLE
Bounded queue hangs for .offerAll when the put size exceeds queue max size

### ISSUE THREAD

**Issue by tampler** [scalaz/scalaz-zio#567]
Hi John

Thanks for building an awesome lib. I started to use it and found a bug in queue implementation.

My code works for small inputs, when the buffer size fits into the bounded queue. However, if I **offerAll()** a large IList, the execution **silently hangs** without any "side effects" and exceptions until Ctrl+C

Here's my project
git clone -b fiberbug https://github.com/tampler/interview_scala

To reproduce:
```bash
sbt testOnly task0.LoopbackUnitTest
```
If you edit /resources/orders.txt and cut it to, say 8 orders and place to /tmp, my code will **happily return**.

Let me know if you need more info

**Comment by ghostdogpr** [comment]
Hi,

This is the expected behavior for the back pressure strategy: `offerAll` will return once all items have been added. If you don’t want to wait and pause the current fiber, you have to use `fork`. See https://scalaz.github.io/scalaz-zio/datatypes/queue.html

**Comment by tampler** [comment]
Hi @ghostdogpr  

Thanks for your oppinion. I disagree. In MY case, the program silently hangs with no signs of a runtime problem. In a larger system, that may be a substantial bug, which is very hard to spot out.

At least a warning should be issued, no? This is a lib design question, so I'm interested in what @jdegoes 
thinks on that behalf. Anyways, you're welcome to offer your solutions to this

**Comment by ghostdogpr** [comment]
@tampler I'm not giving you my opinion, I'm just telling you how it works. It is not a runtime problem: with a Back Pressure strategy, `offerAll` returns an IO that completes once all items have been added to the queue. If you use an unbounded queue or a Dropping or Sliding strategy, `offerAll` will return immediately.

You can refer to this video of John presenting ZIO Queue: https://www.youtube.com/watch?v=8JLprl34xEw&t=0s and the rationale behind it. You'll see most of the examples use `fork`.

**Comment by jdegoes** [comment]
It's true that if you offer more than can fit into the queue, then the offer side is _suspended_ until more room is available; this lets you build "composable backpressure" into your whole application, so producers never completely overwhelm consumers.

Note that it's not an actual _hang_. That is, after your consumers drain enough from the queue that the producers can put their elements in, the producers will resume normally. 

The other model of queuing is "offer and forget", in which the producers do not wait for consumers to catch up. You can get this model with `q.offer(a).fork` / `q.offerAll(as).fork`. In this model, your producers may get so far ahead of consumers that your application is subject to DDoS, including running out of memory and so forth.

Using back-pressured queues comes with its own drawbacks, but not using them also has drawbacks of its own. The ZIO Queue lets you choose the strategy but we need to do a better job documenting this behavior to avoid confusing users who are more familiar with the Java blocking queue interface.

Note also that if you are using queues to perform bidirectional communication between two application components, then using the back pressured queue can render your application susceptible to deadlocks: because the components can each be waiting on each other to process messages from their (full) queues. In my opinion, using queues to bidirectionally transfer messages between components is not a good architecture. Queues work best with acyclic graphs.

**Action Item**: Better documentation for Queue so people understand `offer` / `offerAll` will wait until there's enough room, and they can `fork` the returned `IO` if they want the alternate behavior. Also mention acylic graph note.

**Comment by tampler** [comment]
Thank you for a great explanations. Many newcomers would benefit, if you update Queue docs with a short memo concerning this issue.

As for a DAG design, a commercial product would involve IO to external things, not internal components. 

A short offtopic question: How can I export ZIO web documentation to EPUB or MOBI formats? 

Thank you once again for building, maintaining and supporting this awesome lib
