### ISSUE TITLE
Interrupting cancelable asynchronous resource allocations

### ISSUE THREAD

**Issue by mvv** [scalaz/scalaz-zio#574]
I think it would be useful for the library to make a conceptual distinction between interrupting control flow and interrupting "long" operations. For example, adding a variant of `asyncInterrupt` that is cancelable even inside `.uninterruptible` (at least when `noInterrupt <= 1`) would allow us to use potentially long allocating operations inside `bracket`s `acquire`:
```scala
def acquire(uri: URI): IO[E, R] = IO.interruptible { (k: IO[E, R] => Boolean ) =>
  val future = openIsLongButCancelable(uri)
  future.addListener {
    case Success(resource) =>
      if (!k(IO.succeed(resource))) {
        // Fiber has been interrupted
        resource.close()
      }
    case Failure(e) =>
      k(IO.fail(e))
  }
  Left(IO.succeedLazy(future.cancel()))
}
```
Surely, I don't want to be interrupted on a `flatMap` and leak a freshly allocated resource, but I don't want to waste time allocating things I no longer need either.

**Comment by jdegoes** [comment]
I'm open to doing some work here, but it needs to be extremely well developed because of the potential for resource leaks. @systemfw has some ideas.

Have you considered using `Managed`? Managed lets you describe a resource whose acquisition can be interrupted safely. It's a slightly different pattern than bracket but may accomplish what you're looking for here.

Note that this example has a race condition in it. What if the future returned by `openIsLongButCancelable` has, for all intent and purposes, acquired its resource, but has not yet returned from `Future { ... }`? Or if it is a future from `Promise#future`, then possibly the resource has been acquired, but the line of code which sets the promise has not yet been invoked.

Fundamentally, if you allow examples like this, then they _will_ leak resources _eventually_. The races are small, a matter of microseconds, but they will happen and you can observe them if you repeatedly try in tight loops.

**Comment by mvv** [comment]
* As far as I can tell, only compound (i.e. made with `flatMap`) `Managed` are interruptible, individual `Managed.make` are still uninterruptible in `acquire`. There is a test for that behavior in `ManagedSpec`.
* I could've been more clear about the example. The `future` there is *not* `scala.concurrent.Future`, but something properly designed for cancellation, like Netty's `ChannelFuture`. Anyway, please take a look at #580, it tackles the issue in a more generic way.

**Comment by jdegoes** [comment]
This problem is solved by `Managed` with `reservation`, but examples suggested by @mvv point the way to something more general, #706. Closing this in favor of that one.
