### ISSUE TITLE
Failure to deploy release

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#584]
The release process is not working for the RCN candidates. If anyone has spare cycles, I'd appreciate a look, otherwise I'll get around to it when I can!

**Comment by NeQuissimus** [comment]
I don't currently have the cycles but I don't think an "RC" is allowed as a release artifact. I believe it is similar to "SNAPSHOT" artifacts being considered non-releases.

**Comment by ghostdogpr** [comment]
I had a look at the Travis logs and it seems:

- The RC1 release failed in the middle of uploading the symbols because of a timeout from Sonatype. Seems to be independent from us?
```
java.io.IOException: PUT operation to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scalaz/scalaz-zio-interop-scalaz7x_2.13.0-M5/1.0-RC1/scalaz-zio-interop-scalaz7x_2.13.0-M5-1.0-RC1-javadoc.jar.asc.sha1 failed with status code 504: Gateway Time-out
```
- The RC2 release failed because the artifacts generated were named -RC1 and they already exist.
```
Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/org/scalaz/scalaz-zio-interop-shared_2.13.0-M5/1.0-RC1/scalaz-zio-interop-shared_2.13.0-M5-1.0-RC1-sources.jar'
```

Now what I don't understand is why the RC2 used `-RC1`. Maybe because both are on the same commit? There was a new commit since so maybe we can try an RC3?

**Comment by ghostdogpr** [comment]
The RC3 seems to have deployed properly 😀
2.11: https://repo1.maven.org/maven2/org/scalaz/scalaz-zio_2.11/1.0-RC3/
2.12: https://repo1.maven.org/maven2/org/scalaz/scalaz-zio_2.12/1.0-RC3/
Dotty: https://repo1.maven.org/maven2/org/scalaz/scalaz-zio_0.13/1.0-RC3/

It's not yet visible on Maven Central but I updated by SBT files and it's working already.

**Comment by ghostdogpr** [comment]
Closing this one as RC3 was released successfully.
