### ISSUE TITLE
Fix a sporadic test case in `IOSpec`

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-zio#646]
This test case is flaky and needs to be fixed: 
Check `zipPar` method does not report failure when interrupting loser after it succeeded. 
Sometimes it fails with:
```
[error]  Expected: scalaz.zio.FiberFailure: Fiber failed.
[error]  ╥
[error]  ║
[error]  ╠─The fiber was interrupted
[error]  ▼. Got: scalaz.zio.FiberFailure: Fiber failed.
[error]  ╥
[error]  ║
[error]  ╠══╦══╗
[error]  ║  ║  ║
[error]  ║  ║  ╠─The fiber was interrupted
[error]  ║  ║  ▼
[error]  ║  ║
[error]  ║  ╠─The fiber was interrupted
[error]  ║  ▼
[error]  ▼ instead 
```

**Comment by jdegoes** [comment]
This flaky test looks like it has a race condition. 😢

**Comment by jdegoes** [comment]
Actually the test is correct. What's happening is that a race condition in the runtime is sometimes adding an extra `IO.interrupt` to the failure.

**Comment by jdegoes** [comment]
I take it back. It's the test!!! 😆 

```scala
ZIO.interrupt.zipPar(IO.succeed(1))
```

Sometimes, the left interrupt will cause the right to be interrupted; if it hasn't started executing yet, then we'll get _two_ interrupts, one from the left side, and one from the right side.

I think that's OK. So we need to weaken the test to check that the cause is interrupted, but not look at the exact structure of the Cause.
