### ISSUE TITLE
We got removed from Scala community build 😿

### ISSUE THREAD

**Issue by sideeffffect** [scalaz/scalaz-zio#807]
https://github.com/scala/community-builds/commit/be8d3f07832c78044a65d3840a9338dc05943af7

explanation is given in this thread
https://contributors.scala-lang.org/t/coc-compatible-community-builds/3097

**Comment by jdegoes** [comment]
I'm disappointed in this, because as far as I know, ZIO has only ever had pleasant and professional interactions with the Scala community build.

It's a great loss to the Scala community, because ZIO is really pushing the Scala compiler at the intersection of FP/OOP—but it's nothing we can't deal with. We'll just have to be more vigilant about testing with new versions of the Scala compiler and reporting errors!

Onward ho! 💪

**Comment by sideeffffect** [comment]
fixed in https://github.com/scala/community-builds/pull/831

thanks @jdegoes @SethTisue any everybody who contributed to this! : heart:

**Comment by LGLO** [comment]
I'm afraid it was fixed in January.
I think we should just carry on with working hard and having fun without being part of community build.
Unless scala compiler regression bites us, we are just OK.
However it isn't pleasant feeling.
