### ISSUE TITLE
How to reduce a Vector with ZIO Ref

### ISSUE THREAD

**Issue by tampler** [scalaz/scalaz-zio#832]
Hello

I'm working on an example for a FP programming course. I need to show how to use ZIO Ref to implement a reduce function for Vector[Int]
```scala
def SumZIO (vec:Vector[Int]):Int = ???
```
My current impl is [here](https://github.com/tampler/fp_train/blob/2a33006bb20c3c08e9280634fed3b3ab2f1cf4ab/scala/home/src/main/scala/lec1/solutions/Advanced.scala#L139)

How do I reduce Vector[UIO[Int]] to a single Int with something like reduce (_ + _)
Other solutions are welcome as well.

Thank you!
Boris

**Comment by VladKopanev** [comment]
I think you could do this with smth like `def sum(v: Vector[UIO[Int]]): UIO[Int] =
      for {
        counter <- Ref.make(0)
        _       <- UIO.collectAll(v.map(_.flatMap(i => counter.update(_ + i))))
        res     <- counter.get
      } yield res`
or 
`def sum(v: Vector[UIO[Int]]): UIO[Int] =
      for {
        counter <- Ref.make(0)
        ints       <- UIO.collectAll(v)
        _ <- UIO.foreach(ints)(i => counter.update(_ + i))
        res     <- counter.get
      } yield res`

**Comment by VladKopanev** [comment]
The problem with your current implementation is that each time you do `out flatMap` you actually creating a new shared region for Ref, so new Ref would be created for each vector element. To use a single shared Ref you need to `flatMap` on UIO[Ref[Int]] only once and do all the work inside of that `flatMap` operation. That's because of referential transperency, so your `val out  = makeZero` is equals to `val out  = Ref.make(0)` and your  `out flatMap` consiquently equals to `Ref.make(0) flatMap`

**Comment by iravid** [comment]
Feel free to continue this conversation in the Gitter chatroom - closing this out for now.
